name: Automated Testing - Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build PostgreSQL Stack
        run: docker-compose up -d test-db
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      - name: Run Migrations
        run: yarn db:migrate
        env:
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}

      - name: Run Integration Tests
        run: yarn vitest -c ./vitest.config.integration.ts
        env:
          CI: true
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
